spring:
  cloud:
    config:
      enabled: false
  application:
    name: eshop-customer-order-api
  profiles:
      active: dev
  messages:
      basename: "i18n/messages"
      encoding: UTF-8
  jpa:
    ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQL9Dialect
       hbm2ddl.auto: update
       use_sql_comments: true
       format_sql: false
       show_sql: true
       max_fetch_depth: 5
       jdbc:
         fetch_size: 50
         batch_size: 10
         lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop-customer-order
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
#actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: false

#APP PROPS
order:
  expiredMinutes: 15
cart:
  maxItemsAmount: 3

server:
  port: 8084


